### ISSUE TITLE
Some questions about datasets

### ISSUE THREAD

**Issue by Liqq1** [ahmedeqbal/MDA-Net#1]
Hello! 👋
 There are a few questions about datasets that I would like to ask.
1.How can I find the labels for  RIDER? I could only find images On the official website.(As shown in Fig)
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/54054113/178688431-c2fd423b-bb55-475d-a2da-a6a65e6856ac.png">
2. Is the BUSIS dataset publicly available? If so how can I find it?

I am looking forward to hearing from u！

**Comment by ahmedeqbal** [comment]
1. You can find DICOM masks in "Reference VOI mask", "Anatomical reference" folders
2. you can find BUSIS dataset details here: http://cvprip.cs.usu.edu/busbench/

**Comment by Liqq1** [comment]
Thank you for such a quick reply！
But I still have a few problems. 😭 
1.where can I find  "Reference VOI mask", "Anatomical reference" folders？
2.Is the BUSIS dataset as same as this https://www.kaggle.com/aryashah2k/breast-ultrasound-images-dataset ？
Thanks again！

**Comment by ahmedeqbal** [comment]
1. When you download 400 MB dataset, it includes in each case folder.
2. No, This dataset is not same as BUSIS.

**Comment by Liqq1** [comment]
> * When you download 400 MB dataset, it includes in each case folder.
> * No, This dataset is not same as BUSIS.

1.Each of my folders is 60 images(.dim)

<img width="400" alt="image" src="https://user-images.githubusercontent.com/54054113/178710997-71ded916-c897-4f0b-974d-5ec089fd08b1.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/54054113/178711018-0c87f180-7198-4641-a6ae-0ca226a9eb35.png">

2. Thanks, I see.

**Comment by ahmedeqbal** [comment]
1. Yes, each of your folder includes multiple images, you can manually check segmented once. And create your own version.

**Comment by Liqq1** [comment]
> 1. Yes, each of your folder includes multiple images, you can manually check segmented once. And create your own version.

Sorry, I still don't understand how I'm supposed to find their binary masks(ground truth). (The boxed section in the picture below)
<img width="236" alt="image" src="https://user-images.githubusercontent.com/54054113/178923760-ce428b80-0105-44a5-93dd-ee21cfd02315.png">

Do I need to label them myself?

**Comment by Liqq1** [comment]
> 1. Yes, each of your folder includes multiple images, you can manually check segmented once. And create your own version.

Thank you for your reply😊, my problem has been solved.

**Comment by Liqq1** [comment]
Sorry to bother you again! After going through the dataset I have a few more questions to confirm (as shown below, using the information on one of the patients as an example)
1.When training the model, we use the .dcm files in the "early anatomical reference" as images and the .dcm files in the "reference VOI mask" as labels.
2.Of the three remaining folders, ADC is the apparent dispersion coefficient and the other two are intermediate change processes (we can disregard them when doing segmentation experiments).
Am I understanding the above correctly? Thank you for your unfailing answer.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/54054113/179343430-25955f59-b8e6-410a-9db9-bbab9dd5476f.png">
