### ISSUE TITLE
Excellent work! Please can you provide the code of the comparison method STAN and ESTAN?

### ISSUE THREAD

**Issue by jane442** [ahmedeqbal/MDA-Net#2]
Excellent work! Please can you provide the code of the comparison method STAN and ESTAN? I will appreciate it very much, my email is 1458546594@qq.com

**Comment by ahmedeqbal** [comment]
Dear, 

**STAN** and **ESTAN** networks original implementations are not available. In our paper, we have mentioned their benchmarks results, which are already mentioned in their paper tables. 

Thanks for your comment !

**Comment by jane442** [comment]
Thank you very much for your helpful reply!
